# Generated by Django 3.0.3 on 2020-05-13 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='status',
        ),
        migrations.AddField(
            model_name='music',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='music',
            name='music_video',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='og_singer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.CharField(choices=[('rock', 'ROCK'), ('pop', 'POP'), ('electronic', 'ELECTRONIC'), ('bollywood', 'BOLLYWOOD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.CharField(max_length=100),
        ),
    ]
