# Generated by Django 3.0.6 on 2020-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200513_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='banner',
            field=models.ImageField(default='', upload_to='movies_banner'),
            preserve_default=False,
        ),
    ]
