# Generated by Django 3.0.3 on 2020-05-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='music',
            name='created',
        ),
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.CharField(choices=[('rock', 'ROCK'), ('pop', 'POP'), ('electronic', 'ELECTRONIC'), ('bollywood_romantic', 'BOLLYWOOD ROMANTIC')], max_length=40),
        ),
    ]
