# Generated by Django 3.0.3 on 2020-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200514_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.CharField(choices=[('rock', 'ROCK'), ('pop', 'POP'), ('electronic', 'ELECTRONIC'), ('Bollywood Romantic', 'BOLLYWOOD ROMANTIC'), ('bollywood_singles', 'BOLLYWOOD SINGLES'), ('country', 'COUNTRY')], max_length=40),
        ),
    ]
