# Generated by Django 3.0.3 on 2020-05-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200514_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI'), ('japanese', 'JAPANESE')], max_length=10),
        ),
    ]
