# Generated by Django 3.0.3 on 2020-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200514_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.CharField(choices=[('pop', 'POP'), ('electronic', 'ELECTRONIC'), ('bollywood_romantic', 'BOLLYWOOD ROMANTIC'), ('bollywood_singles', 'BOLLYWOOD SINGLES'), ('country', 'COUNTRY'), ('animated', 'ANIMATED MUSIC VIDEO')], max_length=40),
        ),
    ]
