# Generated by Django 3.0.3 on 2020-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20200515_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, upload_to='music'),
        ),
        migrations.AlterField(
            model_name='musiclink',
            name='link',
            field=models.URLField(default='WATCH'),
        ),
    ]
